### ISSUE TITLE
PA Review: User auth and styling

### ISSUE THREAD

**Issue by CelesteComet** [CelesteComet/Skype#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by CelesteComet** [comment]
Done with auth and frontend auth

**Comment by dwebster17** [comment]
Looks good! Nice work. One thing to fix across the project: Even though you are cloning something, don't put in links that have no functionality and avoid stealing logos. Some specific cases: 

- Remove dummy links from bottom of the page (i.e. terms and conditions & privacy and cookies)
- Remove microsoft logos and microsoft branding, including the favicon microsoft logo. You can replace them with links to your github/linkedin/personal website (once you have one).
![screen shot 2018-02-02 at 4 27 49 pm](https://user-images.githubusercontent.com/29282483/35760602-34d67a3e-0836-11e8-8716-b0e8e5346a97.png)
- Remove promotional emails checkbox

Some other things to work on:

- Don't show the password as the user is typing it--replace it with small dots like most websites. 
- Right now, no matter who you're signing in with, it says "Please enter password for brucewong21". This needs to show the actual user's username
